import quotes from './quotes';

// djb2 hash — returns a positive integer
function hashCode(str) {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash) + str.charCodeAt(i);
    hash = hash & hash; // Convert to 32-bit int
  }
  return Math.abs(hash);
}

// ─── Tarot: 22 Major Arcana ───────────────────────────────────────────────────
export const TAROT_CARDS = [
  {
    name: 'The Fool',
    emoji: '🃏',
    keywords: ['beginnings', 'spontaneity', 'faith', 'innocence'],
    description: 'The Fool represents the start of a new journey, full of excitement and unlimited potential. You stand at the edge of a cliff, ready to leap into the unknown.',
    message: 'Trust the leap. What feels like a risk today is the beginning of your greatest adventure.',
    gradient: ['#a78bfa', '#f472b6'],
  },
  {
    name: 'The Magician',
    emoji: '✨',
    keywords: ['willpower', 'skill', 'manifestation', 'resourcefulness'],
    description: 'The Magician channels divine energy into the material world. You have all the tools you need; the question is whether you will use them.',
    message: 'You are capable of more than you realize. Channel your focus and manifest your vision today.',
    gradient: ['#f59e0b', '#ef4444'],
  },
  {
    name: 'The High Priestess',
    emoji: '🌙',
    keywords: ['intuition', 'mystery', 'subconscious', 'inner knowing'],
    description: 'The High Priestess sits at the threshold between the seen and unseen. She holds the scroll of esoteric knowledge and urges you to listen within.',
    message: 'Your intuition is speaking. Quiet the noise of the world and listen to what your inner wisdom knows.',
    gradient: ['#6366f1', '#0ea5e9'],
  },
  {
    name: 'The Empress',
    emoji: '🌸',
    keywords: ['abundance', 'femininity', 'creativity', 'nurturing'],
    description: 'The Empress represents the fertile earth, creativity in bloom, and the nurturing force of nature. She is abundance personified.',
    message: 'You are surrounded by beauty and abundance. Open your eyes and heart to receive all that life offers.',
    gradient: ['#86efac', '#f9a8d4'],
  },
  {
    name: 'The Emperor',
    emoji: '🏛️',
    keywords: ['authority', 'structure', 'leadership', 'stability'],
    description: 'The Emperor sits upon a stone throne, representing order, authority, and the power to create lasting structures in the world.',
    message: 'Take charge with confidence. Bring order to the areas of your life that feel chaotic.',
    gradient: ['#fbbf24', '#ef4444'],
  },
  {
    name: 'The Hierophant',
    emoji: '🕊️',
    keywords: ['tradition', 'wisdom', 'guidance', 'conformity'],
    description: 'The Hierophant is a spiritual teacher and guide, representing the wisdom of established traditions and the search for deeper meaning.',
    message: 'Seek wisdom from those who have walked before you. A teacher or mentor holds the key you are looking for.',
    gradient: ['#c4b5fd', '#fbbf24'],
  },
  {
    name: 'The Lovers',
    emoji: '💞',
    keywords: ['love', 'harmony', 'choices', 'alignment'],
    description: 'The Lovers card speaks not only of romantic love but of all choices made from the heart — the alignment of values and desires.',
    message: 'Choose with your heart. Whatever decision you face today, let love and authenticity guide you.',
    gradient: ['#f9a8d4', '#fb923c'],
  },
  {
    name: 'The Chariot',
    emoji: '⚡',
    keywords: ['determination', 'control', 'victory', 'willpower'],
    description: 'The Chariot is driven by opposing forces held in perfect tension, symbolizing the triumph of will over conflict and adversity.',
    message: 'You have the strength to overcome. Hold the reins firmly and charge ahead toward your goal.',
    gradient: ['#38bdf8', '#818cf8'],
  },
  {
    name: 'Strength',
    emoji: '🦁',
    keywords: ['courage', 'patience', 'compassion', 'inner power'],
    description: 'Strength shows a woman gently holding a lion\'s mouth — true power is not force, but the quiet confidence that tames even the wildest beast.',
    message: 'True strength is gentle. Lead with compassion today, and you will achieve more than brute force ever could.',
    gradient: ['#fb923c', '#fbbf24'],
  },
  {
    name: 'The Hermit',
    emoji: '🔦',
    keywords: ['soul-searching', 'solitude', 'inner guidance', 'contemplation'],
    description: 'The Hermit climbs a mountain alone, lantern in hand, to seek inner truth. Sometimes the path to wisdom is walked in solitude.',
    message: 'Go within. The answers you seek cannot be found in the noise — only in the quiet of your own reflection.',
    gradient: ['#64748b', '#a78bfa'],
  },
  {
    name: 'Wheel of Fortune',
    emoji: '🎡',
    keywords: ['cycles', 'fate', 'turning point', 'luck'],
    description: 'The Wheel of Fortune reminds us that life moves in cycles — what goes up must come down, and what is down will rise again.',
    message: 'The wheel is turning in your favor. Trust the cycles of life and know that change brings new blessings.',
    gradient: ['#fbbf24', '#34d399'],
  },
  {
    name: 'Justice',
    emoji: '⚖️',
    keywords: ['fairness', 'truth', 'cause and effect', 'clarity'],
    description: 'Justice holds her sword and scales, representing the universal law of cause and effect. Every action has its consequence.',
    message: 'Seek the truth in all you do today. Act with integrity, and the universe will reflect that back to you.',
    gradient: ['#38bdf8', '#6366f1'],
  },
  {
    name: 'The Hanged Man',
    emoji: '🌀',
    keywords: ['pause', 'surrender', 'new perspectives', 'waiting'],
    description: 'The Hanged Man voluntarily suspends himself to gain a new vantage point. True wisdom sometimes comes from doing nothing.',
    message: 'Surrender to where you are. What if a pause is exactly what you need to see everything differently?',
    gradient: ['#818cf8', '#34d399'],
  },
  {
    name: 'Death',
    emoji: '🦋',
    keywords: ['transformation', 'endings', 'transition', 'rebirth'],
    description: 'Death is the card of profound transformation — not physical death, but the necessary ending of one chapter so another can begin.',
    message: 'Something is ending so something better can begin. Trust the transformation unfolding in your life.',
    gradient: ['#1e293b', '#818cf8'],
  },
  {
    name: 'Temperance',
    emoji: '🌊',
    keywords: ['balance', 'moderation', 'patience', 'purpose'],
    description: 'Temperance pours water between two cups, symbolizing the perfect balance between opposing forces and the harmony found in moderation.',
    message: 'Find your flow. Balance and patience will carry you further today than any extreme effort.',
    gradient: ['#38bdf8', '#86efac'],
  },
  {
    name: 'The Devil',
    emoji: '🔗',
    keywords: ['bondage', 'materialism', 'shadow self', 'addiction'],
    description: 'The Devil shows two figures chained — yet the chains are loose. The greatest prison is the one we construct in our own minds.',
    message: 'You are not as trapped as you feel. Examine what you believe holds you back — you may find the chains are loose.',
    gradient: ['#ef4444', '#1e293b'],
  },
  {
    name: 'The Tower',
    emoji: '⚡',
    keywords: ['sudden change', 'upheaval', 'revelation', 'chaos'],
    description: 'The Tower is struck by lightning, its crown toppled. What crashes down was built on false foundations — clearing the way for truth.',
    message: 'What is falling apart was never built to last. Make space for the structures that will truly serve you.',
    gradient: ['#ef4444', '#fbbf24'],
  },
  {
    name: 'The Star',
    emoji: '⭐',
    keywords: ['hope', 'renewal', 'inspiration', 'serenity'],
    description: 'After the storm of the Tower, The Star shines in the clear night sky — a beacon of hope, renewal, and the healing power of simply existing.',
    message: 'Have hope. The universe is conspiring in your favor. You are exactly where you need to be.',
    gradient: ['#818cf8', '#38bdf8'],
  },
  {
    name: 'The Moon',
    emoji: '🌕',
    keywords: ['illusion', 'fear', 'the unconscious', 'confusion'],
    description: 'The Moon illuminates the night but distorts what it reveals. It rules the realm of dreams, intuition, and the fears that lurk in shadow.',
    message: 'Not everything is as it appears. Look beyond your fears to the truth that lies beneath the surface.',
    gradient: ['#c4b5fd', '#1e293b'],
  },
  {
    name: 'The Sun',
    emoji: '☀️',
    keywords: ['joy', 'success', 'vitality', 'clarity'],
    description: 'The Sun radiates pure joy and vitality. A child dances freely beneath its rays — innocent, alive, and in perfect harmony with the world.',
    message: 'Let yourself shine. Today is a day for joy, warmth, and celebrating all that is good in your life.',
    gradient: ['#fbbf24', '#f97316'],
  },
  {
    name: 'Judgement',
    emoji: '📯',
    keywords: ['reflection', 'reckoning', 'awakening', 'absolution'],
    description: 'Judgement calls souls to rise with a trumpet blast. It is the moment of spiritual awakening, of hearing the call to your higher purpose.',
    message: 'You are being called to rise. Listen for the invitation to step fully into who you were meant to be.',
    gradient: ['#f9a8d4', '#818cf8'],
  },
  {
    name: 'The World',
    emoji: '🌍',
    keywords: ['completion', 'integration', 'accomplishment', 'wholeness'],
    description: 'The World is the final card of the Major Arcana — a figure dances in a wreath of victory, having integrated all lessons into wholeness.',
    message: 'You have everything you need within you. This is a time of completion, celebration, and integration.',
    gradient: ['#34d399', '#38bdf8'],
  },
];

// ─── Spirit Animals: 30 ───────────────────────────────────────────────────────
export const SPIRIT_ANIMALS = [
  {
    name: 'Wolf',
    emoji: '🐺',
    medicine: 'Wolf is the pathfinder, the forerunner of new ideas who returns to the clan to teach. Wolf medicine involves facing your inner truth and leading with instinct.',
    message: 'Trust your instincts today. Your inner compass knows the way even when the path isn\'t clear.',
  },
  {
    name: 'Eagle',
    emoji: '🦅',
    medicine: 'Eagle soars highest of all birds and represents a connection to divine spirit and the ability to see the bigger picture from great heights.',
    message: 'Lift your perspective above the day-to-day. What does your situation look like from the eagle\'s view?',
  },
  {
    name: 'Bear',
    emoji: '🐻',
    medicine: 'Bear represents introspection, hibernation as rest and renewal, and the courage to stand firm. Bear medicine calls us to look within and trust our inner knowing.',
    message: 'Honor your need for rest and reflection. Your answers are found in stillness, not in action.',
  },
  {
    name: 'Deer',
    emoji: '🦌',
    medicine: 'Deer brings the energy of gentleness and grace, teaching us that the softest touch can open the most tightly closed heart.',
    message: 'Approach today with gentleness — toward others and especially toward yourself.',
  },
  {
    name: 'Owl',
    emoji: '🦉',
    medicine: 'Owl is the keeper of sacred knowledge, able to see what others cannot in the darkness. Owl medicine is about perceiving the truth beyond illusion.',
    message: 'See clearly what others may miss. Trust the wisdom that comes when you look beyond the obvious.',
  },
  {
    name: 'Butterfly',
    emoji: '🦋',
    medicine: 'Butterfly is the spirit of transformation, carrying the message that no matter how dark the cocoon, beauty always emerges in its time.',
    message: 'You are in a process of becoming. Trust the transformation — your wings are forming right now.',
  },
  {
    name: 'Hawk',
    emoji: '🦆',
    medicine: 'Hawk is the messenger, calling attention to signs and omens from the universe. Hawk sharpens your awareness and sense of spiritual perception.',
    message: 'Pay attention to the signs around you today. The universe is sending messages — are you listening?',
  },
  {
    name: 'Turtle',
    emoji: '🐢',
    medicine: 'Turtle carries its home on its back, representing protection, patience, and the wisdom of moving slowly and deliberately through life.',
    message: 'You don\'t have to rush. Slow down, stay grounded, and trust that you are exactly where you need to be.',
  },
  {
    name: 'Dolphin',
    emoji: '🐬',
    medicine: 'Dolphin embodies the sacred breath of life, joyful communication, and the intelligence of the deep unconscious waters of emotion.',
    message: 'Play and connect today. Joy is not a luxury — it is essential nourishment for your soul.',
  },
  {
    name: 'Fox',
    emoji: '🦊',
    medicine: 'Fox is the shapeshifter, the trickster, and the master of camouflage. Fox medicine teaches adaptability and the art of thinking on your feet.',
    message: 'Be flexible and creative in your approach today. The solution may require a different strategy than you expect.',
  },
  {
    name: 'Horse',
    emoji: '🐴',
    medicine: 'Horse represents power, freedom, and the journey of the soul. Horse medicine calls us to claim our personal power and to move with grace and strength.',
    message: 'Claim your freedom. What would you do if you truly believed you were free to go anywhere?',
  },
  {
    name: 'Raven',
    emoji: '🪶',
    medicine: 'Raven is the keeper of magic and the bringer of light into darkness. Raven carries the gift of foresight and the ability to manifest change.',
    message: 'Magic is real, and it begins with your intention. Set a clear intention today and watch what unfolds.',
  },
  {
    name: 'Swan',
    emoji: '🦢',
    medicine: 'Swan embodies grace, inner beauty, and the ability to accept what is. Swan medicine asks us to surrender to our path rather than fighting the current.',
    message: 'Flow with grace through today\'s challenges. Resistance creates more suffering — trust the current of your life.',
  },
  {
    name: 'Dragonfly',
    emoji: '🌟',
    medicine: 'Dragonfly lives in two worlds — water and air — and represents the ability to look beyond the illusions of the physical world to the deeper truth.',
    message: 'What illusions have you been holding onto? See through them today and step into your authentic truth.',
  },
  {
    name: 'Lion',
    emoji: '🦁',
    medicine: 'Lion is the king of courage, representing personal authority, leadership, and the power of walking boldly in your own truth without apology.',
    message: 'Walk boldly today. You are more powerful than you know — own your gifts and lead from the front.',
  },
  {
    name: 'Hummingbird',
    emoji: '🌺',
    medicine: 'Hummingbird extracts sweetness from every flower and travels impossible distances with tiny wings, teaching us to find joy in the moment and to trust our ability to endure.',
    message: 'Seek the sweetness in every moment today. Joy and wonder are available to you right now.',
  },
  {
    name: 'Salmon',
    emoji: '🐟',
    medicine: 'Salmon swims upstream against all odds, returning home to complete its purpose. Salmon medicine is about determination, inner knowing, and ancestral wisdom.',
    message: 'Keep going, even when you\'re swimming against the current. Your determination will carry you home.',
  },
  {
    name: 'Snake',
    emoji: '🐍',
    medicine: 'Snake sheds its skin and emerges renewed, representing healing, transformation, and the eternal cycle of death and rebirth.',
    message: 'What old skin are you ready to shed? Release what no longer serves and welcome your renewal.',
  },
  {
    name: 'Crow',
    emoji: '🪶',
    medicine: 'Crow is the keeper of sacred law and the bridge between worlds, encouraging us to honor our integrity and to walk our truth without compromise.',
    message: 'Be honest with yourself today. Your highest self knows what is right — listen to it.',
  },
  {
    name: 'Moose',
    emoji: '🦌',
    medicine: 'Moose embodies self-esteem and confidence, the ability to recognize your own gifts and to stand in the wisdom of your own experience.',
    message: 'Celebrate how far you have come. You have earned the right to stand tall in your own life.',
  },
  {
    name: 'Tiger',
    emoji: '🐯',
    medicine: 'Tiger moves with raw power and patience, striking only at the perfect moment. Tiger medicine is about knowing when to act and when to wait.',
    message: 'Patience and power work together. Wait for the right moment, then act with full commitment.',
  },
  {
    name: 'Peacock',
    emoji: '🦚',
    medicine: 'Peacock embodies beauty, confidence, and the ability to transform what has been "ugly" in our lives into spectacular gifts we offer the world.',
    message: 'Show your true colors without shame. The very things you have hidden may be your greatest gifts.',
  },
  {
    name: 'Elephant',
    emoji: '🐘',
    medicine: 'Elephant represents ancient wisdom, memory, and the power of ancestral knowledge. Elephant never forgets and walks its path with deep purpose.',
    message: 'Draw on the wisdom of your ancestors and your own experience. You carry more knowledge than you realize.',
  },
  {
    name: 'Whale',
    emoji: '🐋',
    medicine: 'Whale holds the records of all that has ever been on Earth, singing songs of deep memory and connection to the universal record of existence.',
    message: 'Connect with something larger than yourself today. You are part of an ancient, sacred story.',
  },
  {
    name: 'Jaguar',
    emoji: '🐆',
    medicine: 'Jaguar is the shamanic gatekeeper of the unknown, moving silently between worlds and emerging from darkness with grace and fierce knowing.',
    message: 'Face the unknown without fear. You have an inner power that is more than a match for any darkness.',
  },
  {
    name: 'Rabbit',
    emoji: '🐇',
    medicine: 'Rabbit teaches us to stop creating our own fears and to move gracefully through life by focusing on what we desire rather than what we fear.',
    message: 'Watch what you dwell on — you create what you fear most. Shift your focus to what you truly want.',
  },
  {
    name: 'Otter',
    emoji: '🦦',
    medicine: 'Otter is the playful trickster that reminds us not to take life so seriously, teaching the balance of feminine energy, joy, and sharing.',
    message: 'Approach today with lightness and play. When was the last time you truly let yourself be joyful?',
  },
  {
    name: 'Lynx',
    emoji: '🐱',
    medicine: 'Lynx holds the secrets of hidden knowledge and sees what others cannot, offering the gift of clairvoyance and the wisdom of the unseen.',
    message: 'Trust what you sense but cannot prove. Your subtle perceptions are guiding you correctly.',
  },
  {
    name: 'Crane',
    emoji: '🦩',
    medicine: 'Crane stands for longevity, good fortune, and vigilance, embodying the balance of being both grounded and able to soar to great heights.',
    message: 'Stand tall in your purpose today. You are both rooted and rising.',
  },
  {
    name: 'Buffalo',
    emoji: '🦬',
    medicine: 'Buffalo represents gratitude, abundance, and the sacred understanding that all life is interconnected and that every prayer is answered.',
    message: 'Give thanks for everything you have. Gratitude is the magnet for more abundance in your life.',
  },
];

// ─── Words: 80 ────────────────────────────────────────────────────────────────
export const WORDS = [
  { word: 'Sonder', pronunciation: '/ˈsɒndər/', partOfSpeech: 'noun', definition: 'The realization that each passerby has a life as vivid and complex as one\'s own.', origin: 'Coined by John Koenig in The Dictionary of Obscure Sorrows (2012).', example: 'She felt a wave of sonder watching the strangers rush past her on the subway platform.' },
  { word: 'Hiraeth', pronunciation: '/ˈhɪərɑɪθ/', partOfSpeech: 'noun', definition: 'A Welsh word for a homesickness for somewhere you cannot return to, or perhaps never was.', origin: 'Welsh, from "hir" (long) + "aeth" (going or grief).', example: 'The old photograph filled him with a hiraeth he couldn\'t quite name.' },
  { word: 'Fernweh', pronunciation: '/ˈfɛrnveː/', partOfSpeech: 'noun', definition: 'A German word meaning a longing for faraway places; the opposite of homesickness.', origin: 'German, from "fern" (far) + "Weh" (ache, pain).', example: 'Fernweh seized her every spring, and she began planning another journey.' },
  { word: 'Meraki', pronunciation: '/meˈrɑːki/', partOfSpeech: 'noun', definition: 'A Greek word meaning to do something with soul, creativity, and love — to leave a piece of yourself in your work.', origin: 'Modern Greek, possibly derived from Turkish "merak" (labor of love).', example: 'She cooked every meal with meraki, infusing it with her love and intention.' },
  { word: 'Wanderlust', pronunciation: '/ˈwɒndəlʌst/', partOfSpeech: 'noun', definition: 'A strong desire to travel and explore the world.', origin: 'German, from "wandern" (to wander) + "Lust" (desire, joy).', example: 'Wanderlust consumed her every time she opened her atlas.' },
  { word: 'Eudaimonia', pronunciation: '/juːdaɪˈmoʊniə/', partOfSpeech: 'noun', definition: 'A Greek philosophical term often translated as happiness or flourishing — the condition of human thriving.', origin: 'Ancient Greek, from "eu" (good) + "daimōn" (spirit, deity).', example: 'The philosopher argued that eudaimonia, not pleasure, was the true goal of life.' },
  { word: 'Hygge', pronunciation: '/ˈhjuːɡə/', partOfSpeech: 'noun', definition: 'A Danish and Norwegian concept of coziness and convivial contentment; enjoying the simple pleasures of life with others.', origin: 'Danish/Norwegian, from Old Norse "hugga" (to comfort, to console).', example: 'They embraced hygge on the cold night, gathering around candles with soup and good conversation.' },
  { word: 'Lagom', pronunciation: '/ˈlɑːɡɒm/', partOfSpeech: 'adjective/adverb', definition: 'A Swedish word meaning just the right amount — not too much, not too little, but perfectly balanced.', origin: 'Swedish, believed to derive from "laget om" (around the team).', example: 'The seasoning was lagom — exactly as flavorful as it needed to be.' },
  { word: 'Serendipity', pronunciation: '/ˌsɛrənˈdɪpɪti/', partOfSpeech: 'noun', definition: 'The occurrence of happy or beneficial events by chance.', origin: 'Coined by Horace Walpole in 1754, from the Persian fairy tale "The Three Princes of Serendip."', example: 'It was pure serendipity that she met her best friend waiting for a delayed train.' },
  { word: 'Ephemeral', pronunciation: '/ɪˈfɛm(ə)r(ə)l/', partOfSpeech: 'adjective', definition: 'Lasting for a very short time; transitory.', origin: 'Greek "ephemeros," from "epi" (on) + "hemera" (day).', example: 'Cherry blossoms are ephemeral — here for a week, gone before you want them to be.' },
  { word: 'Solitude', pronunciation: '/ˈsɒlɪtjuːd/', partOfSpeech: 'noun', definition: 'The state of being alone, often chosen for reflection or peace.', origin: 'Latin "solitudo," from "solus" (alone).', example: 'She craved solitude after weeks of constant social obligations.' },
  { word: 'Sanguine', pronunciation: '/ˈsaŋɡwɪn/', partOfSpeech: 'adjective', definition: 'Optimistic or positive, especially in a difficult situation.', origin: 'Old French "sanguin," from Latin "sanguineus" (of blood), referring to the complexion of someone who is optimistic.', example: 'He remained sanguine even when the project ran into obstacles.' },
  { word: 'Mellifluous', pronunciation: '/mɛˈlɪflʊəs/', partOfSpeech: 'adjective', definition: '(Of a voice or music) sweet or musical; pleasant to hear.', origin: 'Latin "mellifluus," from "mel" (honey) + "fluere" (to flow).', example: 'Her mellifluous voice made even difficult news sound gentle.' },
  { word: 'Petrichor', pronunciation: '/ˈpɛtrɪkɔː/', partOfSpeech: 'noun', definition: 'The pleasant smell that often follows rain on warm, dry earth.', origin: 'Greek "petra" (stone) + "ichor" (the fluid that flows through the veins of the gods).', example: 'She stepped outside after the storm, breathing in the petrichor that clung to the air.' },
  { word: 'Liminal', pronunciation: '/ˈlɪmɪn(ə)l/', partOfSpeech: 'adjective', definition: 'Relating to a transitional or initial stage of a process; occupying a position at, or on both sides of, a threshold.', origin: 'Latin "limen" (threshold).', example: 'The year felt liminal — as though she were standing between who she was and who she was becoming.' },
  { word: 'Veridical', pronunciation: '/vəˈrɪdɪk(ə)l/', partOfSpeech: 'adjective', definition: 'Truthful; coinciding with facts; (of a dream or vision) corresponding to what is real.', origin: 'Latin "veridicus," from "verus" (true) + "dicere" (to say).', example: 'The dream felt so veridical that she woke unsure if it had really happened.' },
  { word: 'Susurrus', pronunciation: '/suːˈsʌrəs/', partOfSpeech: 'noun', definition: 'A whispering or murmuring sound.', origin: 'Latin "susurrus" (murmur, whisper).', example: 'The susurrus of the river was the only sound in the forest.' },
  { word: 'Iridescent', pronunciation: '/ˌɪrɪˈdɛs(ə)nt/', partOfSpeech: 'adjective', definition: 'Showing luminous colors that seem to change when seen from different angles.', origin: 'Latin "iris" (rainbow) + "-escent" (becoming).', example: 'The hummingbird\'s throat was iridescent — a flash of emerald and ruby in the sunlight.' },
  { word: 'Crepuscular', pronunciation: '/krɪˈpʌskjʊlə/', partOfSpeech: 'adjective', definition: 'Relating to, resembling, or denoting twilight.', origin: 'Latin "crepusculum" (twilight, dusk).', example: 'She loved the crepuscular hour, when the sky turned lavender and the first stars appeared.' },
  { word: 'Reverie', pronunciation: '/ˈrɛv(ə)ri/', partOfSpeech: 'noun', definition: 'A state of being pleasantly lost in one\'s thoughts; a daydream.', origin: 'French "rêverie," from "rêver" (to dream).', example: 'She sat by the window in a reverie, watching the snow fall without seeing it.' },
  { word: 'Incandescent', pronunciation: '/ˌɪnkænˈdɛs(ə)nt/', partOfSpeech: 'adjective', definition: 'Emitting light as a result of being heated; brilliantly glowing or passionate.', origin: 'Latin "incandescere" (to glow).', example: 'The speaker was incandescent with conviction, and the audience was captivated.' },
  { word: 'Vellichor', pronunciation: '/ˈvɛlɪkɔː/', partOfSpeech: 'noun', definition: 'The strange wistfulness of used bookshops — the awareness that every book has had readers who lived entire lives around it.', origin: 'Coined by John Koenig in The Dictionary of Obscure Sorrows.', example: 'She was seized by vellichor in the old bookshop, pulling out a worn paperback.' },
  { word: 'Alchemy', pronunciation: '/ˈælkɪmi/', partOfSpeech: 'noun', definition: 'The seemingly magical process of transformation or creation; historically, the attempt to turn base metals into gold.', origin: 'Medieval Latin "alchimia," from Arabic "al-kīmiyā."', example: 'There was an alchemy in the way she combined colors on the canvas.' },
  { word: 'Luminous', pronunciation: '/ˈluːmɪnəs/', partOfSpeech: 'adjective', definition: 'Bright or shining, especially in the dark; full of light.', origin: 'Latin "luminosus," from "lumen" (light).', example: 'The full moon cast a luminous glow across the still lake.' },
  { word: 'Numinous', pronunciation: '/ˈnjuːmɪnəs/', partOfSpeech: 'adjective', definition: 'Having a strong religious or spiritual quality; indicating or suggesting the presence of a divinity.', origin: 'Latin "numen" (divine power).', example: 'There was something numinous about the ancient forest that made her speak in whispers.' },
  { word: 'Equanimity', pronunciation: '/ˌɛkwəˈnɪmɪti/', partOfSpeech: 'noun', definition: 'Mental calmness and composure, especially in difficult situations.', origin: 'Latin "aequanimitas," from "aequus" (even) + "animus" (mind).', example: 'She faced the crisis with equanimity, never losing her sense of perspective.' },
  { word: 'Vesper', pronunciation: '/ˈvɛspə/', partOfSpeech: 'noun', definition: 'The evening star; also, an evening prayer or song.', origin: 'Latin "vesper" (evening, evening star).', example: 'They sat on the porch until the vesper star appeared in the darkening sky.' },
  { word: 'Pulchritude', pronunciation: '/ˈpʌlkrɪtjuːd/', partOfSpeech: 'noun', definition: 'Beauty, especially of a person.', origin: 'Latin "pulchritudo," from "pulcher" (beautiful).', example: 'The painting captured a pulchritude that photographs never could.' },
  { word: 'Halcyon', pronunciation: '/ˈhælsiən/', partOfSpeech: 'adjective', definition: 'Denoting a period of time in the past that was idyllically happy and peaceful.', origin: 'Greek "alkuōn" (kingfisher bird), believed to calm the sea during nesting.', example: 'She often looked back on those halcyon summers of childhood.' },
  { word: 'Apricity', pronunciation: '/əˈprɪsɪti/', partOfSpeech: 'noun', definition: 'The warmth of the sun in winter.', origin: 'Latin "apricus" (warmed by the sun); an archaic English term from around 1623.', example: 'She sat on the bench and let the apricity soak into her cold hands.' },
  { word: 'Ineffable', pronunciation: '/ɪˈnɛfəb(ə)l/', partOfSpeech: 'adjective', definition: 'Too great or extreme to be expressed or described in words.', origin: 'Latin "ineffabilis," from "in-" (not) + "effabilis" (utterable).', example: 'The beauty of the sunset was ineffable — she simply stood and wept.' },
  { word: 'Resilience', pronunciation: '/rɪˈzɪlɪəns/', partOfSpeech: 'noun', definition: 'The capacity to recover quickly from difficulties; toughness.', origin: 'Latin "resilire" (to rebound, spring back).', example: 'Her resilience after the loss inspired everyone who witnessed it.' },
  { word: 'Solastalgia', pronunciation: '/ˌsoʊlæˈstældʒə/', partOfSpeech: 'noun', definition: 'Distress caused by environmental change in one\'s home environment.', origin: 'Coined by philosopher Glenn Albrecht, from "solacium" (solace) + "-algia" (pain).', example: 'The drought brought a deep solastalgia to the farmers who had worked the land for generations.' },
  { word: 'Ephemera', pronunciation: '/ɪˈfɛm(ə)rə/', partOfSpeech: 'noun', definition: 'Things that exist or are used or enjoyed for only a short time; items of short-lived interest.', origin: 'Greek "ephemera," neuter plural of "ephemeros" (daily).', example: 'She collected ephemera — tickets, postcards, dried flowers — from every meaningful day.' },
  { word: 'Syzygy', pronunciation: '/ˈsɪzɪdʒi/', partOfSpeech: 'noun', definition: 'A conjunction or opposition, especially of the moon or a planet with the sun; a pair of connected or corresponding things.', origin: 'Greek "suzugia" (yoke, pair).', example: 'The tides surged during the syzygy of sun, earth, and moon.' },
  { word: 'Denouement', pronunciation: '/deɪˈnuːmɒ̃/', partOfSpeech: 'noun', definition: 'The final part of a play, film, or narrative in which the strands of the plot are drawn together and resolved.', origin: 'French "dénouement," from "dénouer" (to unknot).', example: 'The denouement of the novel brought tears to her eyes — everything finally made sense.' },
  { word: 'Hiraeth', pronunciation: '/ˈhɪərɑɪθ/', partOfSpeech: 'noun', definition: 'A longing for home or a past that may never have existed; a blend of homesickness, nostalgia, and grief.', origin: 'Welsh, from "hir" (long) + "aeth" (going, grief).', example: 'The old song filled him with hiraeth for a childhood that was simpler than it had really been.' },
  { word: 'Euphoria', pronunciation: '/juːˈfɔːrɪə/', partOfSpeech: 'noun', definition: 'A feeling or state of intense excitement and happiness.', origin: 'Greek "euphoria," from "eu" (well) + "pherein" (to bear).', example: 'She felt a rush of euphoria crossing the finish line.' },
  { word: 'Serenity', pronunciation: '/sɪˈrɛnɪti/', partOfSpeech: 'noun', definition: 'The state of being calm, peaceful, and untroubled.', origin: 'Latin "serenitas," from "serenus" (clear, calm).', example: 'The mountain lake offered a serenity she had been searching for all year.' },
  { word: 'Catharsis', pronunciation: '/kəˈθɑːsɪs/', partOfSpeech: 'noun', definition: 'The process of releasing strong or repressed emotions through art, story, or other expression.', origin: 'Greek "katharsis" (purification), from "kathairein" (to cleanse).', example: 'Crying through the film was a catharsis she hadn\'t known she needed.' },
  { word: 'Labyrinthine', pronunciation: '/ˌlæbɪˈrɪnθɪn/', partOfSpeech: 'adjective', definition: 'Resembling a labyrinth; highly complex or intricate.', origin: 'Greek "labyrinthos" (labyrinth).', example: 'The old city\'s labyrinthine streets made getting lost a pleasure.' },
  { word: 'Elysian', pronunciation: '/ɪˈlɪziən/', partOfSpeech: 'adjective', definition: 'Of, relating to, or resembling Elysium; blissful, beautiful, or divinely perfect.', origin: 'Latin "Elysium," the dwelling place of the blessed dead in Greek mythology.', example: 'The afternoon was elysian — golden, still, and impossibly beautiful.' },
  { word: 'Acumen', pronunciation: '/ˈækjʊmɪn/', partOfSpeech: 'noun', definition: 'The ability to make good judgments and quick decisions, typically in a particular domain.', origin: 'Latin "acumen" (point, sharpness), from "acuere" (to sharpen).', example: 'Her business acumen was undeniable — she spotted opportunities no one else saw.' },
  { word: 'Awe', pronunciation: '/ɔː/', partOfSpeech: 'noun', definition: 'A feeling of reverential respect mixed with fear or wonder.', origin: 'Old Norse "agi" (terror), Old English "ege" (terror, dread).', example: 'Standing at the edge of the canyon, she was struck mute by awe.' },
  { word: 'Bespoke', pronunciation: '/bɪˈspəʊk/', partOfSpeech: 'adjective', definition: 'Made to order; tailored specifically to individual requirements.', origin: 'Past tense of "bespeak" (to order or arrange in advance), English.', example: 'She wore a bespoke dress that fit her perfectly — like it had been made for her alone.' },
  { word: 'Candor', pronunciation: '/ˈkændə/', partOfSpeech: 'noun', definition: 'The quality of being open and honest in expression; frankness.', origin: 'Latin "candor" (whiteness, brightness), from "candere" (to shine).', example: 'His candor was disarming — he spoke with a directness she rarely encountered.' },
  { word: 'Diaphanous', pronunciation: '/daɪˈæfənəs/', partOfSpeech: 'adjective', definition: 'Light, delicate, and translucent.', origin: 'Greek "diaphanes," from "dia" (through) + "phainein" (to show).', example: 'The diaphanous curtains billowed in the sea breeze, letting light pour through.' },
  { word: 'Enthrall', pronunciation: '/ɪnˈθrɔːl/', partOfSpeech: 'verb', definition: 'To captivate; to hold spellbound.', origin: 'Middle English, from "en-" + "thrall" (slave or captive).', example: 'The storyteller\'s voice enthralled the entire room — no one moved a muscle.' },
  { word: 'Flummox', pronunciation: '/ˈflʌməks/', partOfSpeech: 'verb', definition: 'To bewilder or perplex utterly.', origin: 'Origin unknown, possibly from dialectal English.', example: 'The question flummoxed her so completely she could only laugh.' },
  { word: 'Gossamer', pronunciation: '/ˈɡɒsəmə/', partOfSpeech: 'noun/adjective', definition: 'A fine, delicate, insubstantial material; something light, thin, or delicate.', origin: 'Middle English "gossomer," perhaps from "goose summer" (Indian summer, when goose down floated).', example: 'The spider\'s web was gossamer, barely visible in the morning mist.' },
  { word: 'Halcyon', pronunciation: '/ˈhælsiən/', partOfSpeech: 'adjective', definition: 'Denoting a period of time that was idyllically happy and peaceful.', origin: 'Greek mythological bird believed to nest on the sea and calm the waves.', example: 'Those halcyon summer days felt as though they would never end.' },
  { word: 'Ineffable', pronunciation: '/ɪˈnɛfəb(ə)l/', partOfSpeech: 'adjective', definition: 'Too great or extreme to be expressed or described in words.', origin: 'Latin "ineffabilis," from "in-" (not) + "effabilis" (that which can be uttered).', example: 'She tried to describe the view and failed — it was ineffable.' },
  { word: 'Jubilant', pronunciation: '/ˈdʒuːbɪl(ə)nt/', partOfSpeech: 'adjective', definition: 'Feeling or expressing great happiness and triumph.', origin: 'Latin "jubilans," from "jubilare" (to shout for joy).', example: 'The jubilant crowd poured into the streets after the announcement.' },
  { word: 'Kinship', pronunciation: '/ˈkɪnʃɪp/', partOfSpeech: 'noun', definition: 'A sharing of characteristics or origins; a feeling of being closely related or connected.', origin: 'Old English "cyn" (family, race) + "-ship."', example: 'She felt a kinship with the stranger that surprised them both.' },
  { word: 'Lacuna', pronunciation: '/ləˈkjuːnə/', partOfSpeech: 'noun', definition: 'A gap or missing portion, especially in a manuscript; an unfilled space or interval.', origin: 'Latin "lacuna" (hole, pit, pool).', example: 'There was a lacuna in the historical record — no one knew what happened in those missing months.' },
  { word: 'Mnemonic', pronunciation: '/nɪˈmɒnɪk/', partOfSpeech: 'noun/adjective', definition: 'A device or system, such as a pattern of letters or associations, which assists in remembering something.', origin: 'Greek "mnemonikos," from "mnemon" (mindful), from "mnasthai" (to remember).', example: 'She used a mnemonic to remember the order of the planets.' },
  { word: 'Nascent', pronunciation: '/ˈnæs(ə)nt/', partOfSpeech: 'adjective', definition: 'Just coming into existence and beginning to display signs of future potential.', origin: 'Latin "nascens" (being born), from "nasci" (to be born).', example: 'The nascent idea needed time and care before it was ready to share.' },
  { word: 'Opulent', pronunciation: '/ˈɒpjʊl(ə)nt/', partOfSpeech: 'adjective', definition: 'Ostentatiously rich and luxurious; plentiful or abundant.', origin: 'Latin "opulentus," from "opes" (wealth, resources).', example: 'The banquet hall was opulent — silk, gold, and the fragrance of fresh roses everywhere.' },
  { word: 'Palimpsest', pronunciation: '/ˈpælɪm(p)sɛst/', partOfSpeech: 'noun', definition: 'A manuscript where the original writing has been partly erased and overwritten; something altered but still bearing visible traces of its earlier form.', origin: 'Greek "palimpsestos," from "palin" (again) + "psen" (to rub smooth).', example: 'The old city was a palimpsest — layers of history visible in every crumbling wall.' },
  { word: 'Quixotic', pronunciation: '/kwɪkˈsɒtɪk/', partOfSpeech: 'adjective', definition: 'Exceedingly idealistic; unrealistic and impractical.', origin: 'From Don Quixote, the hero of Cervantes\' 1605 novel.', example: 'Her plan to build a tiny house by hand was considered quixotic by her friends, but she did it.' },
  { word: 'Revenant', pronunciation: '/ˈrɛv(ə)n(ə)nt/', partOfSpeech: 'noun', definition: 'A person who has returned, especially supposedly from the dead; something that returns.', origin: 'French "revenant," from "revenir" (to return).', example: 'She felt like a revenant, returning to the town after twenty years.' },
  { word: 'Sempiternal', pronunciation: '/ˌsɛmpɪˈtəːn(ə)l/', partOfSpeech: 'adjective', definition: 'Eternal and unchanging; everlasting.', origin: 'Latin "semper" (always) + "aeternus" (eternal).', example: 'The stars felt sempiternal — a constant in a world that never stopped changing.' },
  { word: 'Tranquil', pronunciation: '/ˈtraŋkwɪl/', partOfSpeech: 'adjective', definition: 'Free from disturbance; calm.', origin: 'Latin "tranquillus" (calm, quiet).', example: 'The lake at dawn was tranquil — not a ripple on its silver surface.' },
  { word: 'Umbra', pronunciation: '/ˈʌmbrə/', partOfSpeech: 'noun', definition: 'The fully shaded inner region of a shadow cast by an opaque object; the shadow itself.', origin: 'Latin "umbra" (shadow).', example: 'During the eclipse, they stood in the umbra of the moon and the sky turned dark.' },
  { word: 'Verdant', pronunciation: '/ˈvəːd(ə)nt/', partOfSpeech: 'adjective', definition: 'Green with grass or other rich vegetation; inexperienced; unsophisticated.', origin: 'French "verdoyant," from "verdoyer" (to be green), from "verd" (green).', example: 'After the long winter, the valley was suddenly verdant and alive.' },
  { word: 'Wabi-Sabi', pronunciation: '/ˌwɑːbi ˈsɑːbi/', partOfSpeech: 'noun', definition: 'A Japanese aesthetic philosophy of finding beauty in imperfection, transience, and incompleteness.', origin: 'Japanese, from "wabi" (rustic simplicity) + "sabi" (beauty of aging and imperfection).', example: 'The cracked glaze of the bowl embodied wabi-sabi — more beautiful for having been broken and repaired.' },
  { word: 'Xenial', pronunciation: '/ˈziːnɪəl/', partOfSpeech: 'adjective', definition: 'Of or pertaining to hospitality or to the relationship between a host and a guest.', origin: 'Greek "xenia" (hospitality), from "xenos" (stranger, guest).', example: 'She had a xenial spirit — strangers always left her home as friends.' },
  { word: 'Yugen', pronunciation: '/juːˈɡɛn/', partOfSpeech: 'noun', definition: 'A Japanese concept for a profound, mysterious sense of the beauty of the universe and the sad beauty of human suffering.', origin: 'Japanese, from Chinese "youxuan" (deep, profound, or obscure).', example: 'Watching the cranes fly into the twilight, she felt a deep yugen she could not describe.' },
  { id: 79, word: 'Zephyr', pronunciation: '/ˈzɛfə/', partOfSpeech: 'noun', definition: 'A soft, gentle breeze; the west wind personified in Greek mythology.', origin: 'Greek "Zephyros," god of the west wind.', example: 'A zephyr moved through the garden, carrying the scent of jasmine.' },
  { word: 'Aureate', pronunciation: '/ˈɔːrɪɪt/', partOfSpeech: 'adjective', definition: 'Made of gold; brilliant; denoting a highly ornate style of literary writing.', origin: 'Latin "aureus" (golden), from "aurum" (gold).', example: 'The setting sun cast an aureate glow across the cathedral\'s stone facade.' },
  { word: 'Brimborion', pronunciation: '/ˈbrɪmbɒrɪɒn/', partOfSpeech: 'noun', definition: 'A small, worthless trinket or trifle.', origin: 'French "brimborion," of uncertain origin.', example: 'Her desk was covered in brimborions — keychains and tokens from every place she had visited.' },
  { word: 'Callipygian', pronunciation: '/ˌkælɪˈpɪdʒɪən/', partOfSpeech: 'adjective', definition: 'Having well-shaped or beautiful buttocks.', origin: 'Greek "kallipugos," from "kallos" (beauty) + "pugē" (buttocks).', example: 'The statue was famous for its callipygian form, rendered by the sculptor in breathtaking detail.' },
  { word: 'Defenestration', pronunciation: '/dɪˌfɛnɪˈstreɪʃ(ə)n/', partOfSpeech: 'noun', definition: 'The action of throwing someone or something out of a window.', origin: 'Latin "de-" (from) + "fenestra" (window); coined after the Defenestration of Prague (1618).', example: 'The defenestration of the old ideas was long overdue — she had needed a clean break for years.' },
  { word: 'Effulgent', pronunciation: '/ɪˈfʌldʒ(ə)nt/', partOfSpeech: 'adjective', definition: 'Radiant; shining brilliantly.', origin: 'Latin "effulgere" (to shine forth).', example: 'The sun broke through the clouds, effulgent and warm after the long grey days.' },
  { word: 'Flibbertigibbet', pronunciation: '/ˈflɪbətɪˌdʒɪbɪt/', partOfSpeech: 'noun', definition: 'A frivolous, flighty, or excessively talkative person.', origin: 'Middle English, probably an imitative formation representing chatter.', example: 'She was a dear flibbertigibbet — impossible to keep on one topic, but wonderful company.' },
  { word: 'Galvanize', pronunciation: '/ˈɡælvənʌɪz/', partOfSpeech: 'verb', definition: 'Shock or excite someone into taking action; stimulate by or as if by an electric current.', origin: 'After Luigi Galvani, Italian physicist who discovered bioelectricity.', example: 'The speech galvanized the crowd into action before the last note had faded.' },
  { word: 'Hapax Legomenon', pronunciation: '/ˌhapaks lɪˈɡɒmɪnɒn/', partOfSpeech: 'noun', definition: 'A word or form of which only one instance of use is recorded.', origin: 'Greek, "said only once."', example: 'The word appeared only once in the ancient text, making it a hapax legomenon that scholars still debate.' },
];

// ─── Questions: 60 ───────────────────────────────────────────────────────────
export const QUESTIONS = [
  'If you could live your life over again, what would you do differently — and why haven\'t you started doing that now?',
  'What is the difference between the life you are living and the life you want to live?',
  'If your deepest fear came true, would you survive it?',
  'What story are you telling yourself about your life that may not be true?',
  'Who would you be if you had never been told who you should be?',
  'If you had no access to the internet for one year, who would you become?',
  'What are you pretending not to know?',
  'When did you last do something for the first time, and how did it feel?',
  'If the people closest to you described your character, what would they say?',
  'What would you attempt if you knew you could not fail?',
  'What are you most afraid of losing, and why does it have so much power over you?',
  'If you could ask one question and receive a completely truthful answer, what would you ask?',
  'What does a meaningful life look like to you — not in general, but for you specifically?',
  'When you imagine your older self looking back, what will you most wish you had done?',
  'What would you do today if it were your last day of good health?',
  'Are you living from your values or from your fears?',
  'What has been the defining moment of your life so far?',
  'If you could tell the world one thing that you know to be true, what would it be?',
  'What part of yourself have you abandoned along the way to becoming who you are?',
  'What does home mean to you, and do you feel at home in your life?',
  'What relationship in your life most needs attention right now?',
  'If someone observed how you spent your time for the last month, what would they conclude you value most?',
  'What is the kindest thing you could do for yourself this week?',
  'What belief, if you let it go, would free you?',
  'What does joy feel like in your body, and when did you last feel it?',
  'Who are you when no one is watching?',
  'If money were not a factor, how would you spend your time?',
  'What is the most courageous thing you have ever done?',
  'Are you more afraid of failure or of success?',
  'What do you owe yourself that you have been withholding?',
  'What is the quality of your inner voice, and would you speak to a friend the way you speak to yourself?',
  'If your life were a novel, what chapter are you currently in, and what happens next?',
  'What is one thing you have been putting off that, if done, would change everything?',
  'Who do you envy, and what does that tell you about what you want?',
  'When was the last time you changed your mind about something important?',
  'What would you create if no one would ever see it?',
  'What truth do you keep from yourself to avoid discomfort?',
  'Is the life you are living the life that wants to live through you?',
  'What makes you come alive, and are you doing enough of it?',
  'If you could send a message back to yourself ten years ago, what would it say?',
  'What is the bravest thing you could do in the next 24 hours?',
  'What would you need to believe about yourself to take the next step?',
  'Is what you call "who you are" who you really are, or is it who you decided to be?',
  'What parts of yourself have you not yet given yourself permission to express?',
  'Are you seeking approval from someone who will never give it?',
  'What does your soul want that your ego is afraid of?',
  'If your life were a garden, what would be growing and what would need to be pulled out?',
  'What are you still carrying that you were never meant to carry?',
  'If you were already the person you want to be, what would you do today?',
  'What conversation have you been avoiding that could change your life?',
  'Who in your life sees you most clearly, and do you let that be true?',
  'What is the most beautiful thing about being alive that you sometimes forget?',
  'What is the question you are most afraid to ask yourself?',
  'If your purpose found you instead of the other way around, what would it say when it knocked?',
  'What would radical self-acceptance look like in your life right now?',
  'In what area of your life are you playing small?',
  'What would you do if you truly believed you were enough?',
  'How would your day change if you treated every interaction as sacred?',
  'What is the most important thing you have not yet said to someone you love?',
  'If gratitude were a practice, what would you include in tonight\'s prayer?',
];

// ─── Numerology: 1–9 ─────────────────────────────────────────────────────────
export const NUMEROLOGY = [
  {
    number: 1,
    keywords: ['leadership', 'new beginnings', 'independence', 'initiative'],
    description: 'The number 1 is the number of creation and new beginnings. It carries the vibration of the pioneer — bold, independent, and driven by a clear sense of purpose.',
    advice: 'Take the lead today. Trust your instincts and be willing to stand alone in your vision. Something new is asking to be born through you.',
  },
  {
    number: 2,
    keywords: ['partnership', 'balance', 'harmony', 'intuition'],
    description: 'The number 2 holds the frequency of relationship, cooperation, and duality. It is the number of the peacemaker and the bridge-builder.',
    advice: 'Seek balance and collaboration today. Your strength lies in your sensitivity and your willingness to truly listen.',
  },
  {
    number: 3,
    keywords: ['creativity', 'expression', 'joy', 'communication'],
    description: 'The number 3 pulses with creative energy and the joy of self-expression. It is the number of the artist, the communicator, and the child within.',
    advice: 'Express yourself today — through words, art, movement, or laughter. Joy is your spiritual practice.',
  },
  {
    number: 4,
    keywords: ['stability', 'structure', 'discipline', 'foundation'],
    description: 'The number 4 is grounded and reliable, building the foundations upon which dreams become reality. It represents order, security, and the value of dedicated work.',
    advice: 'Focus on building and stabilizing today. Your consistent effort is laying a foundation that will support everything you desire.',
  },
  {
    number: 5,
    keywords: ['freedom', 'change', 'adventure', 'versatility'],
    description: 'The number 5 crackles with the energy of change, curiosity, and freedom. It rules the senses and is drawn to new experiences and the thrill of the unknown.',
    advice: 'Embrace change and flexibility today. Life is inviting you to experience something new — say yes.',
  },
  {
    number: 6,
    keywords: ['love', 'nurturing', 'responsibility', 'home'],
    description: 'The number 6 is the vibration of love, family, and service. It is the most loving of all numbers, deeply devoted to caring for others and creating harmony.',
    advice: 'Nurture your relationships today. Give love freely, but remember that caring for yourself is part of caring for others.',
  },
  {
    number: 7,
    keywords: ['wisdom', 'spirituality', 'introspection', 'mystery'],
    description: 'The number 7 is the seeker — drawn to the deeper mysteries of existence and the pursuit of inner truth. It is the number of the mystic, the philosopher, and the sage.',
    advice: 'Go deeper today. Solitude, meditation, or study will reveal answers that have been just out of reach.',
  },
  {
    number: 8,
    keywords: ['power', 'abundance', 'achievement', 'ambition'],
    description: 'The number 8 is the number of infinite abundance and material mastery. It balances the spiritual and material worlds, understanding that true power serves others.',
    advice: 'Step into your power today with integrity. Success and abundance are natural when effort aligns with purpose.',
  },
  {
    number: 9,
    keywords: ['completion', 'compassion', 'wisdom', 'universal love'],
    description: 'The number 9 is the number of completion and humanitarian service. It has absorbed all previous numbers\' energies and gives back to the world from a place of wholeness.',
    advice: 'Lead with compassion and let go of what is complete. You have wisdom to share — offer it generously.',
  },
];

// ─── Seeding function ─────────────────────────────────────────────────────────
export function getDailyContent(userId, dateStr) {
  function seed(type) {
    return hashCode(userId + dateStr + type);
  }

  const tarot = TAROT_CARDS[seed('tarot') % TAROT_CARDS.length];
  const animal = SPIRIT_ANIMALS[seed('animal') % SPIRIT_ANIMALS.length];
  const quote = quotes[seed('quote') % quotes.length];
  const word = WORDS[seed('word') % WORDS.length];
  const question = QUESTIONS[seed('question') % QUESTIONS.length];
  const numerologyNumber = (seed('number') % 9) + 1;
  const numerology = NUMEROLOGY.find(n => n.number === numerologyNumber);

  return { tarot, animal, quote, word, question, numerology };
}
