export const QUOTE_CATEGORIES = [
  { value: 'all', label: 'All' },
  { value: 'motivation', label: 'Motivation' },
  { value: 'love', label: 'Love' },
  { value: 'travel', label: 'Travel' },
  { value: 'health', label: 'Health' },
  { value: 'career', label: 'Career' },
  { value: 'growth', label: 'Growth' },
  { value: 'spirituality', label: 'Spirituality' },
  { value: 'creativity', label: 'Creativity' },
  { value: 'nature', label: 'Nature' },
];

const quotes = [
  // Motivation (18 original + 22 new = 40)
  { id: 1, text: 'The secret of getting ahead is getting started.', author: 'Mark Twain', category: 'motivation' },
  { id: 2, text: 'It always seems impossible until it\'s done.', author: 'Nelson Mandela', category: 'motivation' },
  { id: 3, text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson', category: 'motivation' },
  { id: 4, text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis', category: 'motivation' },
  { id: 5, text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt', category: 'motivation' },
  { id: 6, text: 'Act as if what you do makes a difference. It does.', author: 'William James', category: 'motivation' },
  { id: 7, text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill', category: 'motivation' },
  { id: 8, text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky', category: 'motivation' },
  { id: 9, text: 'Whether you think you can or you think you can\'t, you\'re right.', author: 'Henry Ford', category: 'motivation' },
  { id: 10, text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', category: 'motivation' },
  { id: 11, text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe', category: 'motivation' },
  { id: 12, text: 'Dream big and dare to fail.', author: 'Norman Vaughan', category: 'motivation' },
  { id: 13, text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 14, text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown', category: 'motivation' },
  { id: 15, text: 'Great things never come from comfort zones.', author: 'Unknown', category: 'motivation' },
  { id: 16, text: 'Wake up with determination. Go to bed with satisfaction.', author: 'Unknown', category: 'motivation' },
  { id: 17, text: 'Little things make big days.', author: 'Unknown', category: 'motivation' },
  { id: 18, text: 'It\'s going to be hard, but hard is not impossible.', author: 'Unknown', category: 'motivation' },
  { id: 104, text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt', category: 'motivation' },
  { id: 105, text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin', category: 'motivation' },
  { id: 106, text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Ryun', category: 'motivation' },
  { id: 107, text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Johann Wolfgang von Goethe', category: 'motivation' },
  { id: 108, text: 'We may encounter many defeats but we must not be defeated.', author: 'Maya Angelou', category: 'motivation' },
  { id: 109, text: 'Genius is one percent inspiration, ninety-nine percent perspiration.', author: 'Thomas Edison', category: 'motivation' },
  { id: 110, text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon', category: 'motivation' },
  { id: 111, text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington', category: 'motivation' },
  { id: 112, text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius', category: 'motivation' },
  { id: 113, text: 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', author: 'Thomas Edison', category: 'motivation' },
  { id: 114, text: 'Too many of us are not living our dreams because we are living our fears.', author: 'Les Brown', category: 'motivation' },
  { id: 115, text: 'I have not failed. I\'ve just found 10,000 ways that won\'t work.', author: 'Thomas Edison', category: 'motivation' },
  { id: 116, text: 'A year from now you may wish you had started today.', author: 'Karen Lamb', category: 'motivation' },
  { id: 117, text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 118, text: 'If you can dream it, you can achieve it.', author: 'Zig Ziglar', category: 'motivation' },
  { id: 119, text: 'You become what you believe.', author: 'Oprah Winfrey', category: 'motivation' },
  { id: 120, text: 'The harder you work for something, the greater you\'ll feel when you achieve it.', author: 'Unknown', category: 'motivation' },
  { id: 121, text: 'Don\'t stop until you\'re proud.', author: 'Unknown', category: 'motivation' },
  { id: 122, text: 'Every accomplishment starts with the decision to try.', author: 'John F. Kennedy', category: 'motivation' },
  { id: 123, text: 'You were born to stand out.', author: 'Dr. Seuss', category: 'motivation' },
  { id: 124, text: 'With the new day comes new strength and new thoughts.', author: 'Eleanor Roosevelt', category: 'motivation' },
  { id: 125, text: 'Setting goals is the first step in turning the invisible into the visible.', author: 'Tony Robbins', category: 'motivation' },

  // Love (16 original + 24 new = 40)
  { id: 19, text: 'The best thing to hold onto in life is each other.', author: 'Audrey Hepburn', category: 'love' },
  { id: 20, text: 'Where there is love there is life.', author: 'Mahatma Gandhi', category: 'love' },
  { id: 21, text: 'The greatest happiness of life is the conviction that we are loved.', author: 'Victor Hugo', category: 'love' },
  { id: 22, text: 'To love and be loved is to feel the sun from both sides.', author: 'David Viscott', category: 'love' },
  { id: 23, text: 'Love is composed of a single soul inhabiting two bodies.', author: 'Aristotle', category: 'love' },
  { id: 24, text: 'The best love is the kind that awakens the soul.', author: 'Nicholas Sparks', category: 'love' },
  { id: 25, text: 'In all the world, there is no heart for me like yours.', author: 'Maya Angelou', category: 'love' },
  { id: 26, text: 'Love is not about how many days, months, or years you have been together.', author: 'Unknown', category: 'love' },
  { id: 27, text: 'You are my today and all of my tomorrows.', author: 'Leo Christopher', category: 'love' },
  { id: 28, text: 'Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', author: 'Lao Tzu', category: 'love' },
  { id: 29, text: 'Love is friendship that has caught fire.', author: 'Ann Landers', category: 'love' },
  { id: 30, text: 'I have found the one whom my soul loves.', author: 'Song of Solomon 3:4', category: 'love' },
  { id: 31, text: 'A loving heart is the truest wisdom.', author: 'Charles Dickens', category: 'love' },
  { id: 32, text: 'Love is the answer, and you know that for sure.', author: 'John Lennon', category: 'love' },
  { id: 33, text: 'Love makes your soul crawl out from its hiding place.', author: 'Zora Neale Hurston', category: 'love' },
  { id: 34, text: 'Fall in love with taking care of yourself — mind, body, and spirit.', author: 'Unknown', category: 'love' },
  { id: 126, text: 'The giving of love is an education in itself.', author: 'Eleanor Roosevelt', category: 'love' },
  { id: 127, text: 'Love all, trust a few, do wrong to none.', author: 'William Shakespeare', category: 'love' },
  { id: 128, text: 'The heart was made to be broken.', author: 'Oscar Wilde', category: 'love' },
  { id: 129, text: 'Love is not love which alters when it alteration finds.', author: 'William Shakespeare', category: 'love' },
  { id: 130, text: 'We loved with a love that was more than love.', author: 'Edgar Allan Poe', category: 'love' },
  { id: 131, text: 'Love is patient, love is kind.', author: '1 Corinthians 13:4', category: 'love' },
  { id: 132, text: 'There is no remedy for love but to love more.', author: 'Henry David Thoreau', category: 'love' },
  { id: 133, text: 'Love takes off masks that we fear we cannot live without and know we cannot live within.', author: 'James Baldwin', category: 'love' },
  { id: 134, text: 'At the touch of love, everyone becomes a poet.', author: 'Plato', category: 'love' },
  { id: 135, text: 'The best proof of love is trust.', author: 'Joyce Brothers', category: 'love' },
  { id: 136, text: 'Love is the only force capable of transforming an enemy into a friend.', author: 'Martin Luther King Jr.', category: 'love' },
  { id: 137, text: 'We accept the love we think we deserve.', author: 'Stephen Chbosky', category: 'love' },
  { id: 138, text: 'To be loved but not known is comforting but superficial. To be known and not loved is our greatest fear.', author: 'Timothy Keller', category: 'love' },
  { id: 139, text: 'Love is not something you find. Love is something that finds you.', author: 'Loretta Young', category: 'love' },
  { id: 140, text: 'If you have only one smile in you, give it to the people you love.', author: 'Maya Angelou', category: 'love' },
  { id: 141, text: 'Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.', author: 'Oscar Wilde', category: 'love' },
  { id: 142, text: 'You know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams.', author: 'Dr. Seuss', category: 'love' },
  { id: 143, text: 'Love yourself first, and everything else falls into line.', author: 'Lucille Ball', category: 'love' },
  { id: 144, text: 'To love is to recognize yourself in another.', author: 'Eckhart Tolle', category: 'love' },
  { id: 145, text: 'There is no charm equal to tenderness of heart.', author: 'Jane Austen', category: 'love' },
  { id: 146, text: 'The emotion that can break your heart is sometimes the very one that heals it.', author: 'Nicholas Sparks', category: 'love' },
  { id: 147, text: 'Love is a canvas furnished by nature and embroidered by imagination.', author: 'Voltaire', category: 'love' },
  { id: 148, text: 'Love isn\'t something you find. Love is something that finds you.', author: 'Loretta Young', category: 'love' },
  { id: 149, text: 'Immature love says: I love you because I need you. Mature love says: I need you because I love you.', author: 'Erich Fromm', category: 'love' },

  // Travel (17 original + 23 new = 40)
  { id: 35, text: 'Not all those who wander are lost.', author: 'J.R.R. Tolkien', category: 'travel' },
  { id: 36, text: 'The world is a book, and those who do not travel read only one page.', author: 'Saint Augustine', category: 'travel' },
  { id: 37, text: 'Travel is the only thing you buy that makes you richer.', author: 'Unknown', category: 'travel' },
  { id: 38, text: 'Adventure is worthwhile in itself.', author: 'Amelia Earhart', category: 'travel' },
  { id: 39, text: 'Life is either a daring adventure or nothing at all.', author: 'Helen Keller', category: 'travel' },
  { id: 40, text: 'To travel is to live.', author: 'Hans Christian Andersen', category: 'travel' },
  { id: 41, text: 'Jobs fill your pocket, but adventures fill your soul.', author: 'Jaime Lyn Beatty', category: 'travel' },
  { id: 42, text: 'Of all the books in the world, the best stories are found between the pages of a passport.', author: 'Unknown', category: 'travel' },
  { id: 43, text: 'Once a year, go someplace you\'ve never been before.', author: 'Dalai Lama', category: 'travel' },
  { id: 44, text: 'We travel not to escape life, but for life not to escape us.', author: 'Unknown', category: 'travel' },
  { id: 45, text: 'The journey not the arrival matters.', author: 'T.S. Eliot', category: 'travel' },
  { id: 46, text: 'Every day is a journey, and the journey itself is home.', author: 'Matsuo Bashō', category: 'travel' },
  { id: 47, text: 'Wherever you go, go with all your heart.', author: 'Confucius', category: 'travel' },
  { id: 48, text: 'Take only memories, leave only footprints.', author: 'Chief Seattle', category: 'travel' },
  { id: 49, text: 'Travel far enough, you meet yourself.', author: 'David Mitchell', category: 'travel' },
  { id: 50, text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu', category: 'travel' },
  { id: 51, text: 'The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.', author: 'Marcel Proust', category: 'travel' },
  { id: 150, text: 'To move, to breathe, to fly, to float, to gain all while you give, to roam the roads of lands remote.', author: 'Kahlil Gibran', category: 'travel' },
  { id: 151, text: 'Man cannot discover new oceans unless he has the courage to lose sight of the shore.', author: 'André Gide', category: 'travel' },
  { id: 152, text: 'Wandering re-establishes the original harmony which once existed between man and the universe.', author: 'Anatole France', category: 'travel' },
  { id: 153, text: 'I haven\'t been everywhere, but it\'s on my list.', author: 'Susan Sontag', category: 'travel' },
  { id: 154, text: 'Blessed are the curious, for they shall have adventures.', author: 'Lovelle Drachman', category: 'travel' },
  { id: 155, text: 'The use of traveling is to regulate imagination by reality, and instead of thinking how things may be, to see them as they are.', author: 'Samuel Johnson', category: 'travel' },
  { id: 156, text: 'Travel makes one modest. You see what a tiny place you occupy in the world.', author: 'Gustave Flaubert', category: 'travel' },
  { id: 157, text: 'Perhaps travel cannot prevent bigotry, but by demonstrating that all peoples cry, laugh, eat, worry, and die, it can introduce the idea that if we try and understand each other, we may even become friends.', author: 'Maya Angelou', category: 'travel' },
  { id: 158, text: 'Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.', author: 'Robert Frost', category: 'travel' },
  { id: 159, text: 'Fill your life with experiences, not things. Have stories to tell, not stuff to show.', author: 'Unknown', category: 'travel' },
  { id: 160, text: 'Own only what you can always carry with you: know languages, know countries, know people.', author: 'Aleksandr Solzhenitsyn', category: 'travel' },
  { id: 161, text: 'He who does not travel does not know the value of men.', author: 'Moorish Proverb', category: 'travel' },
  { id: 162, text: 'I travel not to go anywhere, but to go. I travel for travel\'s sake.', author: 'Robert Louis Stevenson', category: 'travel' },
  { id: 163, text: 'Life is short and the world is wide.', author: 'Simon Raven', category: 'travel' },
  { id: 164, text: 'Do not follow where the path may lead. Go instead where there is no path and leave a trail.', author: 'Muriel Strode', category: 'travel' },
  { id: 165, text: 'Adventure awaits.', author: 'Unknown', category: 'travel' },

  // Health (16 original + 24 new = 40)
  { id: 52, text: 'Take care of your body. It\'s the only place you have to live.', author: 'Jim Rohn', category: 'health' },
  { id: 53, text: 'Health is not about the weight you lose, but about the life you gain.', author: 'Unknown', category: 'health' },
  { id: 54, text: 'Your body hears everything your mind says.', author: 'Naomi Judd', category: 'health' },
  { id: 55, text: 'Nourish to flourish.', author: 'Unknown', category: 'health' },
  { id: 56, text: 'Exercise is a celebration of what your body can do, not a punishment for what you ate.', author: 'Unknown', category: 'health' },
  { id: 57, text: 'A healthy outside starts from the inside.', author: 'Robert Urich', category: 'health' },
  { id: 58, text: 'The groundwork of all happiness is health.', author: 'Leigh Hunt', category: 'health' },
  { id: 59, text: 'Wellness is the complete integration of body, mind, and spirit.', author: 'Greg Anderson', category: 'health' },
  { id: 60, text: 'Sleep is the best meditation.', author: 'Dalai Lama', category: 'health' },
  { id: 61, text: 'An apple a day keeps the doctor away.', author: 'Benjamin Franklin', category: 'health' },
  { id: 62, text: 'It is health that is real wealth and not pieces of gold and silver.', author: 'Mahatma Gandhi', category: 'health' },
  { id: 63, text: 'To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear.', author: 'Buddha', category: 'health' },
  { id: 64, text: 'Rest when you\'re weary. Refresh and renew yourself, your body, your mind, your spirit.', author: 'Ralph Marston', category: 'health' },
  { id: 65, text: 'Eat well, travel often, love deeply, sleep soundly.', author: 'Unknown', category: 'health' },
  { id: 66, text: 'Mental health is just as important as physical health.', author: 'Unknown', category: 'health' },
  { id: 67, text: 'Your wellbeing is a priority. Your happiness is essential. Your care is necessary.', author: 'Unknown', category: 'health' },
  { id: 166, text: 'The greatest wealth is health.', author: 'Virgil', category: 'health' },
  { id: 167, text: 'Happiness is the highest form of health.', author: 'Dalai Lama', category: 'health' },
  { id: 168, text: 'He who has health has hope, and he who has hope has everything.', author: 'Arabian Proverb', category: 'health' },
  { id: 169, text: 'Let food be thy medicine, and let medicine be thy food.', author: 'Hippocrates', category: 'health' },
  { id: 170, text: 'Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.', author: 'John F. Kennedy', category: 'health' },
  { id: 171, text: 'A good laugh and a long sleep are the best cures in the doctor\'s book.', author: 'Irish Proverb', category: 'health' },
  { id: 172, text: 'The body is a self-healing organism, so it\'s really about clearing things out of the way so the body can heal itself.', author: 'Barbara Brennan', category: 'health' },
  { id: 173, text: 'Investing in your health will produce enormous benefits.', author: 'Unknown', category: 'health' },
  { id: 174, text: 'Movement is a medicine for creating change in a person\'s physical, emotional, and mental states.', author: 'Carol Welch', category: 'health' },
  { id: 175, text: 'No matter how slow you go, you are still lapping everybody on the couch.', author: 'Unknown', category: 'health' },
  { id: 176, text: 'Health is a relationship between you and your body.', author: 'Terri Guillemets', category: 'health' },
  { id: 177, text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi', category: 'health' },
  { id: 178, text: 'To enjoy the glow of good health, you must exercise.', author: 'Gene Tunney', category: 'health' },
  { id: 179, text: 'Early to bed and early to rise makes a man healthy, wealthy, and wise.', author: 'Benjamin Franklin', category: 'health' },
  { id: 180, text: 'Balance is not something you find; it\'s something you create.', author: 'Jana Kingsford', category: 'health' },
  { id: 181, text: 'Breathe deeply, until sweet air extinguishes the burn of fear in your lungs.', author: 'Tara Westover', category: 'health' },
  { id: 182, text: 'Self-care is not self-indulgence, it is self-preservation.', author: 'Audre Lorde', category: 'health' },
  { id: 183, text: 'Almost everything will work again if you unplug it for a few minutes, including you.', author: 'Anne Lamott', category: 'health' },
  { id: 184, text: 'You don\'t have to be extreme, just consistent.', author: 'Unknown', category: 'health' },
  { id: 185, text: 'Progress, not perfection.', author: 'Unknown', category: 'health' },
  { id: 186, text: 'An hour of meditation a day is essential, except when you are very busy. Then you need two hours.', author: 'Old Zen Saying', category: 'health' },
  { id: 187, text: 'Rest is not idleness, and to lie sometimes on the grass under trees on a summer\'s day, is by no means a waste of time.', author: 'John Lubbock', category: 'health' },
  { id: 188, text: 'Taking care of yourself is part of taking care of others.', author: 'Unknown', category: 'health' },
  { id: 189, text: 'Water, air, and cleanliness are the chief articles in my pharmacopoeia.', author: 'Napoleon Bonaparte', category: 'health' },

  // Career (16 original + 24 new = 40)
  { id: 68, text: 'Choose a job you love, and you will never have to work a day in your life.', author: 'Confucius', category: 'career' },
  { id: 69, text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs', category: 'career' },
  { id: 70, text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau', category: 'career' },
  { id: 71, text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson', category: 'career' },
  { id: 72, text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser', category: 'career' },
  { id: 73, text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee', category: 'career' },
  { id: 74, text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller', category: 'career' },
  { id: 75, text: 'I attribute my success to this: I never gave or took any excuse.', author: 'Florence Nightingale', category: 'career' },
  { id: 76, text: 'Hustle until your haters ask if you\'re hiring.', author: 'Unknown', category: 'career' },
  { id: 77, text: 'Work hard in silence, let your success be your noise.', author: 'Frank Ocean', category: 'career' },
  { id: 78, text: 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.', author: 'Steve Jobs', category: 'career' },
  { id: 79, text: 'Ambition is the path to success. Persistence is the vehicle you arrive in.', author: 'Bill Bradley', category: 'career' },
  { id: 80, text: 'If you really look closely, most overnight successes took a long time.', author: 'Steve Jobs', category: 'career' },
  { id: 81, text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair', category: 'career' },
  { id: 82, text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt', category: 'career' },
  { id: 83, text: 'The best way to predict the future is to create it.', author: 'Abraham Lincoln', category: 'career' },
  { id: 190, text: 'The secret to getting ahead is getting started.', author: 'Agatha Christie', category: 'career' },
  { id: 191, text: 'Without ambition one starts nothing. Without work one finishes nothing.', author: 'Ralph Waldo Emerson', category: 'career' },
  { id: 192, text: 'You can\'t use up creativity. The more you use, the more you have.', author: 'Maya Angelou', category: 'career' },
  { id: 193, text: 'Don\'t limit your challenges. Challenge your limits.', author: 'Unknown', category: 'career' },
  { id: 194, text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney', category: 'career' },
  { id: 195, text: 'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.', author: 'Charles Darwin', category: 'career' },
  { id: 196, text: 'Your time is limited, so don\'t waste it living someone else\'s life.', author: 'Steve Jobs', category: 'career' },
  { id: 197, text: 'The function of leadership is to produce more leaders, not more followers.', author: 'Ralph Nader', category: 'career' },
  { id: 198, text: 'Management is doing things right; leadership is doing the right things.', author: 'Peter Drucker', category: 'career' },
  { id: 199, text: 'Talent wins games, but teamwork and intelligence win championships.', author: 'Michael Jordan', category: 'career' },
  { id: 200, text: 'The more I want to get something done, the less I call it work.', author: 'Richard Bach', category: 'career' },
  { id: 201, text: 'Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea. This is the way to success.', author: 'Swami Vivekananda', category: 'career' },
  { id: 202, text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill', category: 'career' },
  { id: 203, text: 'Do what you can, where you are, with what you have.', author: 'Theodore Roosevelt', category: 'career' },
  { id: 204, text: 'It always seems impossible until it\'s done.', author: 'Nelson Mandela', category: 'career' },
  { id: 205, text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson', category: 'career' },
  { id: 206, text: 'Clarity of vision is the key to achieving your objectives.', author: 'Tom Steyer', category: 'career' },
  { id: 207, text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein', category: 'career' },
  { id: 208, text: 'Never give up on something that you can\'t go a day without thinking about.', author: 'Winston Churchill', category: 'career' },
  { id: 209, text: 'All progress takes place outside the comfort zone.', author: 'Michael John Bobak', category: 'career' },
  { id: 210, text: 'Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.', author: 'William James', category: 'career' },
  { id: 211, text: 'Problems are not stop signs, they are guidelines.', author: 'Robert H. Schuller', category: 'career' },
  { id: 212, text: 'Don\'t raise your voice, improve your argument.', author: 'Desmond Tutu', category: 'career' },
  { id: 213, text: 'Quality means doing it right when no one is looking.', author: 'Henry Ford', category: 'career' },

  // Growth (20 original + 20 new = 40)
  { id: 84, text: 'Be yourself; everyone else is already taken.', author: 'Oscar Wilde', category: 'growth' },
  { id: 85, text: 'In the middle of every difficulty lies opportunity.', author: 'Albert Einstein', category: 'growth' },
  { id: 86, text: 'The only person you should try to be better than is the person you were yesterday.', author: 'Unknown', category: 'growth' },
  { id: 87, text: 'You cannot go back and change the beginning, but you can start where you are and change the ending.', author: 'C.S. Lewis', category: 'growth' },
  { id: 88, text: 'Life isn\'t about finding yourself. Life is about creating yourself.', author: 'George Bernard Shaw', category: 'growth' },
  { id: 89, text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein', category: 'growth' },
  { id: 90, text: 'Two roads diverged in a wood, and I — I took the one less traveled by.', author: 'Robert Frost', category: 'growth' },
  { id: 91, text: 'You must be the change you wish to see in the world.', author: 'Mahatma Gandhi', category: 'growth' },
  { id: 92, text: 'The only limit to our realization of tomorrow is our doubts of today.', author: 'Franklin D. Roosevelt', category: 'growth' },
  { id: 93, text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson', category: 'growth' },
  { id: 94, text: 'Challenges are what make life interesting and overcoming them is what makes life meaningful.', author: 'Joshua J. Marine', category: 'growth' },
  { id: 95, text: 'Everything you can imagine is real.', author: 'Pablo Picasso', category: 'growth' },
  { id: 96, text: 'The most common form of despair is not being who you are.', author: 'Søren Kierkegaard', category: 'growth' },
  { id: 97, text: 'Do not go where the path may lead; go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson', category: 'growth' },
  { id: 98, text: 'She believed she could, so she did.', author: 'R.S. Grey', category: 'growth' },
  { id: 99, text: 'Your time is limited, don\'t waste it living someone else\'s life.', author: 'Steve Jobs', category: 'growth' },
  { id: 100, text: 'It\'s never too late to be what you might have been.', author: 'George Eliot', category: 'growth' },
  { id: 101, text: 'The woman who follows the crowd will usually go no further than the crowd. The woman who walks alone is likely to find herself in places no one has ever been.', author: 'Albert Einstein', category: 'growth' },
  { id: 102, text: 'Be the energy you want to attract.', author: 'Unknown', category: 'growth' },
  { id: 103, text: 'Bloom where you are planted.', author: 'Unknown', category: 'growth' },
  { id: 214, text: 'The secret of change is to focus all of your energy, not on fighting the old, but on building the new.', author: 'Socrates', category: 'growth' },
  { id: 215, text: 'If you want to fly, give up everything that weighs you down.', author: 'Buddha', category: 'growth' },
  { id: 216, text: 'The cave you fear to enter holds the treasure you seek.', author: 'Joseph Campbell', category: 'growth' },
  { id: 217, text: 'Rock bottom became the solid foundation on which I rebuilt my life.', author: 'J.K. Rowling', category: 'growth' },
  { id: 218, text: 'We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.', author: 'Maya Angelou', category: 'growth' },
  { id: 219, text: 'The mind is everything. What you think you become.', author: 'Buddha', category: 'growth' },
  { id: 220, text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle', category: 'growth' },
  { id: 221, text: 'We must be willing to let go of the life we planned so as to have the life that is waiting for us.', author: 'Joseph Campbell', category: 'growth' },
  { id: 222, text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb', category: 'growth' },
  { id: 223, text: 'No mud, no lotus.', author: 'Thich Nhat Hanh', category: 'growth' },
  { id: 224, text: 'Change your thoughts and you change your world.', author: 'Norman Vincent Peale', category: 'growth' },
  { id: 225, text: 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', author: 'Roy T. Bennett', category: 'growth' },
  { id: 226, text: 'To improve is to change; to be perfect is to change often.', author: 'Winston Churchill', category: 'growth' },
  { id: 227, text: 'Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don\'t belong.', author: 'Mandy Hale', category: 'growth' },
  { id: 228, text: 'What you resist persists.', author: 'Carl Jung', category: 'growth' },
  { id: 229, text: 'Stop being afraid of what could go wrong and think of what could go right.', author: 'Unknown', category: 'growth' },
  { id: 230, text: 'Your life is a reflection of your thoughts. If you change your thinking, you change your life.', author: 'Brian Tracy', category: 'growth' },
  { id: 231, text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi', category: 'growth' },
  { id: 232, text: 'The wound is the place where the light enters you.', author: 'Rumi', category: 'growth' },
  { id: 233, text: 'Incredible change happens in your life when you decide to take control of what you do have power over instead of craving control over what you don\'t.', author: 'Steve Maraboli', category: 'growth' },

  // Spirituality (25 new)
  { id: 234, text: 'The soul that sees beauty may sometimes walk alone.', author: 'Johann Wolfgang von Goethe', category: 'spirituality' },
  { id: 235, text: 'Be still and know that I am God.', author: 'Psalm 46:10', category: 'spirituality' },
  { id: 236, text: 'In the middle of difficulty lies opportunity and divinity.', author: 'Unknown', category: 'spirituality' },
  { id: 237, text: 'The quieter you become, the more you can hear.', author: 'Ram Dass', category: 'spirituality' },
  { id: 238, text: 'Wherever you are is the entry point.', author: 'Kabir', category: 'spirituality' },
  { id: 239, text: 'The spiritual path is simply the journey of living our lives. Everyone is on a spiritual path; most people just don\'t know it.', author: 'Marianne Williamson', category: 'spirituality' },
  { id: 240, text: 'We are not human beings having a spiritual experience. We are spiritual beings having a human experience.', author: 'Pierre Teilhard de Chardin', category: 'spirituality' },
  { id: 241, text: 'The present moment is the only moment available to us, and it is the door to all moments.', author: 'Thich Nhat Hanh', category: 'spirituality' },
  { id: 242, text: 'God is closer to you than you think.', author: 'Unknown', category: 'spirituality' },
  { id: 243, text: 'Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.', author: 'Rumi', category: 'spirituality' },
  { id: 244, text: 'The soul becomes dyed with the color of its thoughts.', author: 'Marcus Aurelius', category: 'spirituality' },
  { id: 245, text: 'Out beyond ideas of wrongdoing and rightdoing, there is a field. I\'ll meet you there.', author: 'Rumi', category: 'spirituality' },
  { id: 246, text: 'Awakening is not changing who you are, but discarding who you are not.', author: 'Deepak Chopra', category: 'spirituality' },
  { id: 247, text: 'The kingdom of God is within you.', author: 'Luke 17:21', category: 'spirituality' },
  { id: 248, text: 'If you light a lamp for someone else, it will also brighten your path.', author: 'Buddha', category: 'spirituality' },
  { id: 249, text: 'Do not be conformed to this world, but be transformed by the renewal of your mind.', author: 'Romans 12:2', category: 'spirituality' },
  { id: 250, text: 'Be a lamp, or a lifeboat, or a ladder. Help someone\'s soul heal.', author: 'Rumi', category: 'spirituality' },
  { id: 251, text: 'Let the beauty of what you love be what you do.', author: 'Rumi', category: 'spirituality' },
  { id: 252, text: 'When you realize there is nothing lacking, the whole world belongs to you.', author: 'Lao Tzu', category: 'spirituality' },
  { id: 253, text: 'Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig.', author: 'Marcus Aurelius', category: 'spirituality' },
  { id: 254, text: 'Prayer is not asking. It is a longing of the soul.', author: 'Mahatma Gandhi', category: 'spirituality' },
  { id: 255, text: 'Your sacred space is where you can find yourself again and again.', author: 'Joseph Campbell', category: 'spirituality' },
  { id: 256, text: 'The privilege of a lifetime is to become who you truly are.', author: 'Carl Jung', category: 'spirituality' },
  { id: 257, text: 'Gratitude unlocks the fullness of life.', author: 'Melody Beattie', category: 'spirituality' },
  { id: 258, text: 'Not all those who wander are lost — some are seeking the divine.', author: 'Unknown', category: 'spirituality' },

  // Creativity (25 new)
  { id: 259, text: 'Creativity is intelligence having fun.', author: 'Albert Einstein', category: 'creativity' },
  { id: 260, text: 'Every child is an artist. The problem is how to remain an artist once we grow up.', author: 'Pablo Picasso', category: 'creativity' },
  { id: 261, text: 'You can\'t wait for inspiration. You have to go after it with a club.', author: 'Jack London', category: 'creativity' },
  { id: 262, text: 'Art enables us to find ourselves and lose ourselves at the same time.', author: 'Thomas Merton', category: 'creativity' },
  { id: 263, text: 'To practice any art, no matter how well or badly, is a way to make your soul grow. So do it.', author: 'Kurt Vonnegut', category: 'creativity' },
  { id: 264, text: 'The creative adult is the child who survived.', author: 'Ursula K. Le Guin', category: 'creativity' },
  { id: 265, text: 'Imagination is more important than knowledge.', author: 'Albert Einstein', category: 'creativity' },
  { id: 266, text: 'A blank page is not empty; it is full of possibilities.', author: 'Unknown', category: 'creativity' },
  { id: 267, text: 'Color is my day-long obsession, joy, and torment.', author: 'Claude Monet', category: 'creativity' },
  { id: 268, text: 'Logic will get you from A to B. Imagination will take you everywhere.', author: 'Albert Einstein', category: 'creativity' },
  { id: 269, text: 'Begin with the end in mind, then create everything in between.', author: 'Stephen Covey', category: 'creativity' },
  { id: 270, text: 'The worst enemy to creativity is self-doubt.', author: 'Sylvia Plath', category: 'creativity' },
  { id: 271, text: 'Creativity requires the courage to let go of certainties.', author: 'Erich Fromm', category: 'creativity' },
  { id: 272, text: 'There is no innovation and creativity without failure. Period.', author: 'Brené Brown', category: 'creativity' },
  { id: 273, text: 'Make visible what, without you, might perhaps never have been seen.', author: 'Robert Bresson', category: 'creativity' },
  { id: 274, text: 'Creativity is not a talent; it is a way of operating.', author: 'John Cleese', category: 'creativity' },
  { id: 275, text: 'The desire to create is one of the deepest yearnings of the human soul.', author: 'Dieter F. Uchtdorf', category: 'creativity' },
  { id: 276, text: 'An idea that is not dangerous is unworthy of being called an idea at all.', author: 'Oscar Wilde', category: 'creativity' },
  { id: 277, text: 'The painter has the Universe in his mind and hands.', author: 'Leonardo da Vinci', category: 'creativity' },
  { id: 278, text: 'If you hear a voice within you say, "You cannot paint," then by all means paint, and that voice will be silenced.', author: 'Vincent van Gogh', category: 'creativity' },
  { id: 279, text: 'Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.', author: 'Scott Adams', category: 'creativity' },
  { id: 280, text: 'When all else is lost, the future still remains.', author: 'Christian Nestell Bovee', category: 'creativity' },
  { id: 281, text: 'Clean out a corner of your mind and creativity will instantly fill it.', author: 'Dee Hock', category: 'creativity' },
  { id: 282, text: 'Creativity is the power to connect the seemingly unconnected.', author: 'William Plomer', category: 'creativity' },
  { id: 283, text: 'Do something wonderful. People may imitate it.', author: 'Albert Schweitzer', category: 'creativity' },

  // Nature (25 new)
  { id: 284, text: 'In every walk with nature, one receives far more than he seeks.', author: 'John Muir', category: 'nature' },
  { id: 285, text: 'The Earth does not belong to us; we belong to the Earth.', author: 'Chief Seattle', category: 'nature' },
  { id: 286, text: 'Look deep into nature, and then you will understand everything better.', author: 'Albert Einstein', category: 'nature' },
  { id: 287, text: 'Nature always wears the colors of the spirit.', author: 'Ralph Waldo Emerson', category: 'nature' },
  { id: 288, text: 'Adopt the pace of nature: her secret is patience.', author: 'Ralph Waldo Emerson', category: 'nature' },
  { id: 289, text: 'The clearest way into the Universe is through a forest wilderness.', author: 'John Muir', category: 'nature' },
  { id: 290, text: 'If you truly love nature, you will find beauty everywhere.', author: 'Vincent van Gogh', category: 'nature' },
  { id: 291, text: 'One touch of nature makes the whole world kin.', author: 'William Shakespeare', category: 'nature' },
  { id: 292, text: 'Earth laughs in flowers.', author: 'Ralph Waldo Emerson', category: 'nature' },
  { id: 293, text: 'There is a pleasure in the pathless woods, there is a rapture on the lonely shore.', author: 'Lord Byron', category: 'nature' },
  { id: 294, text: 'Wild rivers are earth\'s renegades, defying gravity, dancing to their own tunes.', author: 'Richard Bangs', category: 'nature' },
  { id: 295, text: 'To sit in the shade on a fine day and look upon verdure is the most perfect refreshment.', author: 'Jane Austen', category: 'nature' },
  { id: 296, text: 'The mountains are calling and I must go.', author: 'John Muir', category: 'nature' },
  { id: 297, text: 'I go to nature to be soothed and healed, and to have my senses put in order.', author: 'John Burroughs', category: 'nature' },
  { id: 298, text: 'In all things of nature there is something of the marvelous.', author: 'Aristotle', category: 'nature' },
  { id: 299, text: 'Keep close to Nature\'s heart... and break clear away, once in awhile, and climb a mountain or spend a week in the woods.', author: 'John Muir', category: 'nature' },
  { id: 300, text: 'The ocean is a mighty harmonist.', author: 'William Wordsworth', category: 'nature' },
  { id: 301, text: 'A flower does not think of competing with the flower next to it. It just blooms.', author: 'Zen Shin', category: 'nature' },
  { id: 302, text: 'Trees are poems that the earth writes upon the sky.', author: 'Kahlil Gibran', category: 'nature' },
  { id: 303, text: 'The sun does not shine for a few trees and flowers, but for the wide world\'s joy.', author: 'Henry Ward Beecher', category: 'nature' },
  { id: 304, text: 'Water is the driving force of all nature.', author: 'Leonardo da Vinci', category: 'nature' },
  { id: 305, text: 'Spring is nature\'s way of saying, "Let\'s party!"', author: 'Robin Williams', category: 'nature' },
  { id: 306, text: 'Rest is not idleness, and to lie sometimes on the grass under the trees on a summer\'s day, listening to the murmur of water, is by no means a waste of time.', author: 'John Lubbock', category: 'nature' },
  { id: 307, text: 'Storms make trees take deeper roots.', author: 'Dolly Parton', category: 'nature' },
  { id: 308, text: 'The poetry of the earth is never dead.', author: 'John Keats', category: 'nature' },
];

export function getQuotes(category = 'all', searchTerm = '') {
  let result = category === 'all' ? quotes : quotes.filter(q => q.category === category);
  if (searchTerm.trim()) {
    const term = searchTerm.toLowerCase();
    result = result.filter(
      q => q.text.toLowerCase().includes(term) || q.author.toLowerCase().includes(term)
    );
  }
  return result;
}

export default quotes;
